# app/services/skills_lexicon.py
LEXICON = {
    "python": ["python", "py"],
    "javascript": ["javascript", "js"],
    "typescript": ["typescript", "ts"],
    "react": ["react"],
    "redux": ["redux"],
    "node.js": ["node.js", "nodejs", "node"],
    "django": ["django"],
    "flask": ["flask"],
    "java": ["java"],
    "spring": ["spring", "springboot", "spring boot"],
    "c++": ["c++"],
    "c#": ["c#"],
    "go": ["golang", "go"],
    "sql": ["sql", "t-sql"],
    "postgresql": ["postgresql", "postgres"],
    "mysql": ["mysql"],
    "mongodb": ["mongodb"],
    "nosql": ["nosql", "dynamodb", "cassandra", "cosmos db", "redis"],
    "rest": ["rest", "restful", "rest api", "rest apis"],
    "graphql": ["graphql"],
    "mvc": ["mvc"],
    "git": ["git", "github", "gitlab", "bitbucket"],
    "linux": ["linux", "unix"],
    "bash": ["bash", "shell", "shell scripting"],
    "docker": ["docker"],
    "kubernetes": ["kubernetes", "k8s"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration", "continuous delivery", "continuous deployment"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure", "microsoft azure"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "rest api": ["rest api", "restful api"],
    "redis": ["redis"],
    "kafka": ["kafka"],
    "terraform": ["terraform"],
}

CANONICAL_ORDER = list(LEXICON.keys())
